[[bin]]
name = "app-main"
path = "app/main.rs"

[package]
name = "azure-cosmos-db-nosql-rust-quickstart"
edition = "2021"

[dependencies]
axum = "0.8.9"
azure_data_cosmos = { version = "0.32.0", features = ["key_auth"] }
azure_core = "0.34.0"
dotenv = "0.15.0"
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
socketioxide = "0.18.3"
tokio = { version = "1.52.1", features = ["rt", "net", "rt-multi-thread", "macros"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["cors", "fs"] }
